sources:
  - name: tbtc-mainnet
    handler:
      graphql:
        endpoint: https://threshold-api-staging.ops-keep.workers.dev/subgraph/mainnet
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql
